services:
  db:
    image: mysql:8.0
    container_name: diplom_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
      MYSQL_USER: diplom_user
      MYSQL_PASSWORD: diplom_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    build:
      context: ./Server        # ← вот здесь заглавная “S”
    container_name: diplom_api
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: diplom_user
      DB_PASSWORD: diplom_pass
      DB_NAME: store
      PORT: 5000
    depends_on:
      - db
    ports:
      - "5000:5000"

  client:
    build:
      context: ./Client        # ← и здесь заглавная “C”
    container_name: diplom_client
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "3000:80"

volumes:
  db_data:
