# 1) Сборка зависимостей
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --production
COPY . .

# 2) Продукционный образ
FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app .
# порт берётся из ENV, но экспонируем 5000
EXPOSE 5000
CMD ["node", "index.js"]
